JustUtahCoders/utahexpungements.org

- src/app/forms/petition-for-conviction/petition-for-conviction.pdf.component.js
- src/app/forms/petition-for-conviction/petition-for-conviction.web.component.js
, added counties then created function to auto-populate the judicial district
> added fields for district and justice court

- src/app/forms/inputs/radio.component.js
- src/app/forms/inputs/select.component.js
- src/app/forms/petition-for-conviction/petition-for-conviction.pdf.component.js
- src/app/forms/petition-for-conviction/petition-for-conviction.web.component.js
- src/firebase/firebase.js
Created radio component for the forms court type selection.
Added class name to select component to make the style in line with the rest of the form.
Removed checkbox and added radio buttons to form. 
Removed Fire-base timestampsInSnapshots as this is know the default
> Petition to expunge continuation 

- src/app/forms/bank/form-list.component.js
- src/app/forms/petition-for-conviction/petition-for-conviction.pdf.component.js
Corrected date and printed name locations, moved form to ready for use
> Finishing up expungement conviction form

- src/app/forms/draft-court-order-conviction/draft-court-order-conviction.pdf.component.js
- src/app/forms/draft-court-order-conviction/draft-court-order-conviction.web.component.js
Removed section 3, added some context for judges name not being necessary.
> Cleaned up the court order conviction, base off Tuckers input.

- src/app/forms/draft-court-order-conviction/draft-court-order-conviction.pdf.component.js
- src/app/forms/draft-court-order-conviction/draft-court-order-conviction.web.component.js
- src/app/forms/form-common-options/districtCourts.json
- src/app/forms/form-common-options/form-common-options.js
- src/app/forms/form-common-options/justiceCourts.json
Looking for feedback on this before I add this to the rest of the forms.
> adding address lookup based off of court type and county

- src/app/forms/acceptance-of-service/acceptance-of-service.pdf.component.js
- src/app/forms/acceptance-of-service/acceptance-of-service.web.component.js
- src/app/forms/petition-for-drug-conviction/petition-for-drug-conviction.web.component.js
> Finishing Acceptance of Service Form.

- .prettierignore
See https://travis-ci.org/JustUtahCoders/utahexpungements.org/builds/593814212
> Fixing prettier check error

- frontend/app/forms/inputs/text-input-group.component.js
- frontend/app/forms/motion-to-waive-fees/motion-to-waive-fees.pdf.component.js
- frontend/app/forms/motion-to-waive-fees/motion-to-waive-fees.web.component.js
> Started text input group

- frontend/app/forms/bank/form-bank.component.js
- frontend/app/forms/bank/form-list.component.js
- frontend/app/forms/draft-court-order-drug-possession-conviction/draft-court-order-drug-possession-conviction.pdf.component.js
Looks like there are only two forms that aren't fully finished. Looks like some of the others might need some work.
> updating the form bank to show the correct forms that are done

- .eslintrc
- frontend/app/banner.component.js
- frontend/app/docket-pdf/docket-pdf.component.js
- frontend/app/forms/bank/fillable-form.component.js
- frontend/app/forms/form-common-options/form-common-options.js
- frontend/app/forms/inputs/text-area.component.js
- frontend/app/forms/inputs/text-input-group.component.js
- frontend/app/forms/inputs/text-input.component.js
- frontend/app/forms/render-page.component.js
- frontend/app/overview/vocabulary/defined-term.component.js
- frontend/app/overview/vocabulary/vocabulary.component.js
- frontend/app/user/cases-list.component.js
- frontend/app/utils/accordion.component.js
- frontend/home/detail-highlight.component.js
- frontend/navbar/hamburger.component.js
- package-lock.json
- package.json
- webpack.config.js
- yarn.lock
Closes #117 
* added eslint
* added `joeldenning/eslint-config-react-important-stuff`
* fixed up .eslintrc
* husky/lint-staged for frontend
* added `yarn lint`
_currently only eslint for frontend (need to configure for ejs and node to further checks for backend)_
> feature: eslint added and fixed a few eslint errors

- frontend/app/forms/proof-of-completed-service/proof-of-completed-service.web.component.js
Fixed data keys on prior sections & completed section 4.
Proof of Completed Service - web components form complete.
> fixed data keys on prior sections & completed section 4. 

- frontend/app/user/cases-list.component.js
- frontend/app/user/people-list.component.js
- frontend/firebase/database.js
Location: /app/dashboard
Before: delete button didn't do anything.
After when button clicked:
- deletes case from database
- deletes case from browser for seamless UI
- if current case is deleted, `context.activePerson` and `context.activeCase` get updated to `""`
> Wired delete button (#120)

- frontend/footer/footer.component.js
columns were a little close together
> spacing fix on footer

- frontend/styleguide.js
We were getting an unneeded side to side scroll
> removed extra side scroll

- frontend/navbar/menu-items.component.js
suggestion for the order of the sidebar items
> sidebar order suggestion

- frontend/home/detail-highlight.component.js
- frontend/home/home.component.js
some alignment adjustments and adding links and titles to the images
> Home page UX suggestions

- backend/apis/flag-utils/is-debt-collection-util.js
- backend/apis/generate-flag-json.utils.js
Addresses https://github.com/JustUtahCoders/utahexpungements.org/issues/144
Checks whether applicant has been sent to debt collection
> Debt Collection Flag

- backend/apis/flag-utils/is-class-b-misdemeanor.js
- backend/apis/generate-flag-json.utils.js
Addresses https://github.com/JustUtahCoders/utahexpungements.org/issues/141
I just put this up real quick, still need to review it, but thought I'd put it up here to get some eyes on it to make sure I'm going the right direction.
@benschinn are there any tests I should run to make sure nothing broke?
@tuckersamuelsen does a "Class B Misdemeanor" always show up with this capitalization?
Also, I'm first counting the _charges_ to check that there are 4 or more. Then I loop through the _charges_ to see if there are at least 3 that are Class B. The description says to check the _convictions_ rather than _charges_ so wanted to check if I'm doing that right.
> add class b misdemeanor flag

- backend/apis/flag-utils/is-automobile-homicide.js
- backend/apis/generate-flag-json.utils.js
Created file to check if automobile-homicide && imported into generate-flag-json.utils.js
> Checking if automobile-homicide

- frontend/app/forms/bank/form-list.component.js
Form was already completed. Updated the flag so this form is available for the user on the site.
> make active for user

- backend/apis/flag-utils/is-class-a-misdemeanor.js
- backend/apis/generate-flag-json.utils.js
I tried my best to create a function based off of the law. I'm pretty sure that we either need to be able to process multiple dockets at once or have a different counting system in place, other than true/false object.
**Law:**
> (b) any combination of three or more convictions
> other than for drug possession offenses
> that include two class A misdemeanor convictions,
> each of which is contained in a separate criminal episode;
**This is pseudo code I wrote that I based my final function on:**
```
Flag = FALSE
Convictions = {
class_a_misdemeanor:0,
plain:0
}
Convictions per docket:
Skip if "drug possession offense" found
Return plain++ if felony or any other conviction found
Return class_a_misdemeanor++ if "class A misdemeanor conviction" found
Multiple dockets:
Return Flag(TRUE) if …
```
> created isClassAMisdemeanor flag function

- backend/apis/flag-utils/is-first-degree-felony-flag-util.js
- backend/apis/generate-flag-json.utils.js
- backend/apis/parse-docket-pdf.api.js
I need some help on the logic for the first degree felony flag.
> initial work on 1st degree felony flag

- backend/apis/parse-docket-pdf.api.js
this MR addresses:
1. properly handling multiple files for raw output
2. properly setting filesize limit (it was set as 10bytes by mistake when it should be 10mb)
3. adding filename param for debuggability purposes to json format
> Multiple file upload bug fix and refactor

- package.json
See related https://travis-ci.org/github/JustUtahCoders/utahexpungements.org/jobs/662060495#L456
> Fixing build by changing node engine

- frontend/app/forms/proof-of-completed-service/proof-of-completed-service.pdf.component.js
> fix urls of page 4/5 in Proof of Completed Service

- frontend/app/forms/draft-court-order-motion-waive-fees/draft-court-order-motion-waive-fees.web.component.js
- frontend/app/forms/motion-to-waive-fees/motion-to-waive-fees.pdf.component.js
- frontend/app/forms/motion-to-waive-fees/motion-to-waive-fees.web.component.js
- frontend/app/forms/order-on-petition-charges-not-filed/order-on-petition-charges-not-filed.pdf.component.js
- frontend/app/forms/order-on-petition-charges-not-filed/order-on-petition-charges-not-filed.web.component.js
- frontend/app/forms/order-on-petition-to-expunge-records/order-on-petition-to-expunge-records.pdf.component.js
- frontend/app/forms/order-on-petition-to-expunge-records/order-on-petition-to-expunge-records.web.component.js
- frontend/app/forms/proof-of-completed-service/proof-of-completed-service.pdf.component.js
- frontend/app/forms/proof-of-completed-service/proof-of-completed-service.web.component.js
- frontend/app/forms/reply-to-statement/reply-to-statement.pdf.component.js
- frontend/app/forms/reply-to-statement/reply-to-statement.web.component.js
- frontend/app/forms/special-bci/special-bci.pdf.component.js
- frontend/app/forms/special-bci/special-bci.web.component.js
Issue 6 in https://github.com/JustUtahCoders/utahexpungements.org/issues/183
Fixed inconsistent use of "person.phone" and "person.homePhone"
> fix inconsistent dataKeys for phone numbers

- frontend/app/forms/district-court-cover-sheet/district-court-cover-sheet.pdf.component.js
This is issue 5 in https://github.com/JustUtahCoders/utahexpungements.org/issues/183
> add checkmark on URCP26 exemption in district court cover sheet

- frontend/app/forms/form-common-options/JusticeCourtList.json
Addresses items 1 and 12 in issue https://github.com/JustUtahCoders/utahexpungements.org/issues/183
* Added commas between street addresses
* Fixed incorrect addresses e.g. sandy justice court
* removed unnecessary white spacing
> Fixing Addresses and formatting

- frontend/app/forms/application-for-board-of-pardon-e/application-for-board-of-pardon-e.pdf.component.js
- frontend/app/forms/motion-to-waive-fees/motion-to-waive-fees.pdf.component.js
- frontend/app/forms/petition-for-charges-never-filed/petition-for-charges-never-filed.pdf.component.js
- frontend/app/forms/petition-for-conviction/petition-for-conviction.pdf.component.js
- frontend/app/forms/petition-for-dismissal-or-acquittal/petition-for-dismissal-or-acquittal.pdf.component.js
Addressing #2 in issue https://github.com/JustUtahCoders/utahexpungements.org/issues/183
> Removing Autofilled Dates in Form

- frontend/app/forms/district-court-cover-sheet/district-court-cover-sheet.pdf.component.js
- frontend/app/forms/district-court-cover-sheet/district-court-cover-sheet.web.component.js
- frontend/app/forms/justice-court-cover-sheet/justice-court-cover-sheet.pdf.component.js
- frontend/app/forms/justice-court-cover-sheet/justice-court-cover-sheet.web.component.js
Added defendant/respondent to Justice Court Cover Sheet and District Court Cover Sheet. 
This is issue 3 in https://github.com/JustUtahCoders/utahexpungements.org/issues/183
> Add defendant on coversheets

- frontend/app/forms/bank/form-bank.component.js
- frontend/app/forms/bank/form-list.component.js
- frontend/app/forms/draft-court-order-drug-possession-conviction/draft-court-order-drug-possession-conviction.pdf.component.js
- frontend/app/forms/draft-court-order-motion-waive-fees/draft-court-order-motion-waive-fees.pdf.component.js
- frontend/app/forms/draft-court-order-motion-waive-fees/draft-court-order-motion-waive-fees.web.component.js
- frontend/i18n/en.js
Added a few changes to this branch to address 9, 10 and 15 in https://github.com/JustUtahCoders/utahexpungements.org/issues/183
> Order on motion to waive fees

- frontend/app/forms/order-on-motion-for-reduction-of-conviction/order-on-motion-for-reduction-of-conviction.pdf.component.js
- frontend/app/forms/order-on-motion-for-reduction-of-conviction/order-on-motion-for-reduction-of-conviction.web.component.js
Issue 17 in https://github.com/JustUtahCoders/utahexpungements.org/issues/183
> remove resolve dropdown menu in Order on Motion for Reduction of Conviction

- frontend/app/forms/draft-court-order-conviction/draft-court-order-conviction.pdf.component.js
- frontend/app/forms/draft-court-order-drug-possession-conviction/draft-court-order-drug-possession-conviction.pdf.component.js
- frontend/app/forms/order-on-petition-charges-not-filed/order-on-petition-charges-not-filed.pdf.component.js
- frontend/app/forms/order-on-petition-charges-not-filed/order-on-petition-charges-not-filed.web.component.js
- frontend/app/forms/order-on-petition-to-expunge-records/order-on-petition-to-expunge-records.pdf.component.js
- frontend/app/forms/order-on-petition-to-expunge-records/order-on-petition-to-expunge-records.web.component.js
- frontend/app/forms/petition-for-expungement-from-bci/petition-for-expungement-from-bci.pdf.component.js
- frontend/app/forms/petition-for-expungement-from-bci/petition-for-expungement-from-bci.web.component.js
This addresses issue 7 and 17 of #183 Form Bank Issues 
This should resolve the issue of having a "resolved by pleadings or hearing" checked. This needs to be left blank for the judge to fill out.
> removed resolved by pleadings or hearing

- frontend/app/forms/inputs/form-that-prints.component.js
This addresses item 11 of Form Bank Issues #183. Created alert to trigger reminder to print two copies on Petition forms only.
> first pass on reminder to print two copies

- frontend/app/forms/form-common-options/JusticeCourtList.json
> Correct South Jordan court address

- frontend/app/forms/district-court-cover-sheet/district-court-cover-sheet.pdf.component.js
- frontend/app/forms/form-common-options/JusticeCourtList.json
Issue 23 in https://github.com/JustUtahCoders/utahexpungements.org/issues/202
> Remove jury demand checkbox

- frontend/app/forms/form-common-options/JusticeCourtList.json
> fixed court address

- frontend/home/home.component.js
Not sure this is what you want, but trying to help with some low hanging fruit.
> Issue #176: Removed beta tester email field
